kind: ConfigMap
apiVersion: v1
metadata:
  name: dd-agent-config
  namespace: default
data:
  istio-config: |-
    init_config:
    instances:
    - istio_mesh_endpoint: http://localhost:42422/metrics
      mixer_endpoint: http://localhost:9093/metrics
      send_histograms_buckets: true
